### PR TITLE
Maybe this?

### PR DESCRIPTION
**Pull request by dustinswales**

### CODE REVIEW

**Comment by climbfuji** [comment]
@dustinswales I cherry-picked the commit and resolved the conflict for testing. As I expected, it doesn't work for module variables declared in the group:
```
[100%] Built target test_host
At line 216 of file /Users/heinzell/work/ccpp-framework/ccpp-framework-debug-20231012/test/capgen_test/test_host.F90
Fortran runtime warning: An array temporary was created
 Available suites are:
1) ddt_suite = test_suites(2)
2) temp_suite = test_suites(1)
 Checking suite temp_suite
 Checking suite ddt_suite
At line 223 of file /Users/heinzell/work/ccpp-framework/ccpp-framework-debug-20231012/test/ct_build/ccpp/ccpp_temp_suite_cap.F90
Fortran runtime error: Index '6' of dimension 1 of array 'temp_level' above upper bound of 5
```
I'll try to find out if I can add some minimal logic to determine if it's a group module variable and if so, adjust the bounds. Otherwise I'll revert.

**Comment by climbfuji** [comment]
Unfortunately I couldn't find a good solution that was less manual than what I have now.

**Comment by dustinswales** [comment]
@climbfuji I just reran the capgen_test using Intel w/o error.
During init:
Screenshot 2023-11-27 at 9 40 46 AM
During run:
Screenshot 2023-11-27 at 9 41 00 AM

**Comment by climbfuji** [comment]
You need to rerun ALL tests: cd test && ./run_fortran_tests.sh

**Pull request closed without merging**
